### DISCUSSION TITLE
Gruvbox theme?

### DISCUSSION THREAD

**Discussion by gshpychka** [lsd-rs/lsd#1013] [Q&A] [answered]
Thank you for the tool, it's awesome. Could anyone please share a good Gruvbox (dark) theme?

**Comment by Aeron** [comment]
The first problem is that it uses [xterm-256 colors](https://upload.wikimedia.org/wikipedia/commons/1/15/Xterm_256color_chart.svg), which consist of 16 base system (ANSI) colors and other non-system colors, and those do not remotely correspond to any Gruvbox variants. Custom hexadecimal or RGB values are not an option. Thus, you can only configure it out of your terminal colors. Or try to build an approximation, yet I’m not sure it can be close enough, but maybe I’m wrong.

The second problem is that it uses theme colors for many things except file types. These still solely depend on the `LS_COLORS` environment variable. Thus, you probably will need to configure it separately.

I’m not sure it’d be helpful, but here is how it works for me. I’m using the Base16 variant of the Gruvbox in my terminal. It looks like this:

<img width="316" alt="Gruvbox Dark (Base16) ANSI Colors" src="https://github.com/lsd-rs/lsd/assets/278423/0fe2df6f-e18e-4fa0-b759-16a99d1010f6">

```text
0: 282828
1: FB4934
2: B8BB26
3: FABD2F
4: 83A598
5: D3869B
6: 8EC07C
7: D5C4A1
8: 665C54
9: FE8019
10: 3C3836
11: 504945
12: BDAE93
13: EBDBB2
14: D65D0E
15: FBF1C7
```

And I keep my `colors.yaml` pretty minimal since I don’t like to change colors for different dates, sizes, and permissions. It looks like the following:

```yaml
user: 0
group: 0
permission:
  read: 14
  write: 14
  exec: 14
  exec-sticky: 14
  no-access: 14
date:
  hour-old: 2
  day-old: 2
  older: 2
size:
  none: 3
  small: 3
  medium: 3
  large: 3
inode:
  valid: 0
  invalid: 0
links:
  valid: 0
  invalid: 0
tree-edge: 0
```

So, in my case, the final result looks like this:

<img width="528" alt="LSD command colored example output" src="https://github.com/lsd-rs/lsd/assets/278423/c0601845-aaff-4989-8480-0b546221e3af">

I didn’t bother with the `LS_COLORS` since I thought the file type colors would eventually be configurable in theme colors. And it determines how the directories and files look. And somehow, the permission’s directory indicator as well (#574).
