### DISCUSSION TITLE
Color dosen't show on windows

### DISCUSSION THREAD

**Discussion by swp-nil** [lsd-rs/lsd#1092] [General]
I tried using dracula color that didn't work either. 
I tried placing the config at at `~/.config/lsd/` or `C:\Users\username\AppData\Roaming\lsd\` neither works..  both config and colors file in the same dir.

`config.yaml`:
```yaml

classic: false
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

color:
  when: always
  theme: custom

date: date
dereference: false

icons:
  when: always
  theme: fancy
  separator: " "

indicators: false

layout: oneline

recursion:

  enabled: false

size: default

sorting:

  column: name

  reverse: false

  dir-grouping: first


no-symlink: false

total-size: false

hyperlink: never

symlink-arrow: ⇒

header: false

literal: false

truncate-owner:

  after:

  marker: ""
```

`colors.yaml`:
```yaml
user: 159                           # cyan
group: 231                          # foreground
permission:
  read: 183                         # blue
  write: 212                        # magenta
  exec: 159                         # cyan
  exec-sticky: 159                  # cyan
  no-access: 210                    # red
date:
  hour-old: 146                     # comment 20% lighter
  day-old: 103                      # comment
  older: 60                         # current line
size:
  none: 60                          # current line
  small: 120                        # green
  medium: 215                       # orange
  large: 210                        # red
inode:
  valid: 231                        # foreground
  invalid: 210                      # red
links:
  valid: 159                        # cyan
  invalid: 210                      # red
tree-edge: 183                      # blue
```
