### DISCUSSION TITLE
How to target specific folder to change icons?

### DISCUSSION THREAD

**Discussion by rahaaatul** [lsd-rs/lsd#1100] [Q&A] [answered]
For example, if I do:

```yaml
filetype:
  dir: 📂
```
It targets all directory but leaves out some folders

![image](https://github.com/user-attachments/assets/172f6b2e-ab34-4469-8e4b-0bf440ae75ad)

and my question is how to target these special folders on windows?

**Comment by rahaaatul** [comment, marked as answer]
Found the solution:

###### `icons.yaml`
```yaml
name:
  desktop: 💻
  documents: 📃
  downloads: 📥
  music: 🎧
  pictures: 🖼️
  videos: 🎥

filetype:
  dir: 📂
```

###### Preview
![image](https://github.com/user-attachments/assets/a3c3d893-abd6-43ae-8ff2-c549d0fef6b0)
