### ISSUE TITLE
[Bug]: `lsd -al` - Operation not permitted (os error 1).

### ISSUE THREAD

**Issue by stivens13** [lsd-rs/lsd#1078]
- os: MacOS 14.5 (23F79)
- `lsd --version`: latest - 1.1.2
-  `installation`: `brew install lsd`
- `echo $TERM`: xterm-256color
- `echo $LS_COLORS`: empty
No other environment variables present for either `ls` or `lsd`

<details>
  <summary>lsd config content ~/.config/lsd/config.yml</summary>

  ```
# == Classic ==
# This is a shorthand to override some of the options to be backwards compatible
# with `ls`. It affects the "color"->"when", "sorting"->"dir-grouping", "date"
# and "icons"->"when" options.
# Possible values: false, true
classic: false

# == Blocks ==
# This specifies the columns and their order when using the long and the tree
# layout.
# Possible values: permission, user, group, context, size, date, name, inode, links, git
blocks:
  - permission
  - user
  - group
  - size
  - date
  - name

# == Color ==
# This has various color options. (Will be expanded in the future.)
color:
  # When to colorize the output.
  # When "classic" is set, this is set to "never".
  # Possible values: never, auto, always
  when: auto
  # How to colorize the output.
  # When "classic" is set, this is set to "no-color".
  # Possible values: default, custom
  # When "custom" is set, lsd will look in the config directory for `colors.yaml`.
  theme: default

# == Date ==
# This specifies the date format for the date column. The freeform format
# accepts a strftime like string.
# When "classic" is set, this is set to "date".
# Possible values: date, locale, relative, '+<date_format>'
# `date_format` will be a `strftime` formatted value. e.g. `date: '+%d %b %y %X'` will give you a date like this: 17 Jun 21 20:14:55
date: date

# == Dereference ==
# Whether to dereference symbolic links.
# Possible values: false, true
dereference: false

# == Display ==
# What items to display. Do not specify this for the default behavior.
# Possible values: all, almost-all, directory-only
# display: all

# == Icons ==
icons:
  # When to use icons.
  # When "classic" is set, this is set to "never".
  # Possible values: always, auto, never
  when: auto
  # Which icon theme to use.
  # Possible values: fancy, unicode
  theme: fancy
  # Separator between icon and the name
  # Default to 1 space
  separator: " "

# == Ignore Globs ==
# A list of globs to ignore when listing.
# ignore-globs:
#   - .git

# == Indicators ==
# Whether to add indicator characters to certain listed files.
# Possible values: false, true
indicators: false

# == Layout ==
# Which layout to use. "oneline" might be a bit confusing here and should be
# called "one-per-line". It might be changed in the future.
# Possible values: grid, tree, oneline
layout: grid

# == Recursion ==
recursion:
  # Whether to enable recursion.
  # Possible values: false, true
  enabled: false
  # How deep the recursion should go. This has to be a positive integer. Leave
  # it unspecified for (virtually) infinite.
  # depth: 3

# == Size ==
# Specifies the format of the size column.
# Possible values: default, short, bytes
size: default

# == Permission ==
# Specify the format of the permission column
# Possible value: rwx, octal, attributes (windows only), disable
# permission: rwx

# == Sorting ==
sorting:
  # Specify what to sort by.
  # Possible values: extension, name, time, size, version
  column: extension
  # Whether to reverse the sorting.
  # Possible values: false, true
  reverse: false
  # Whether to group directories together and where.
  # When "classic" is set, this is set to "none".
  # Possible values: first, last, none
  dir-grouping: first

# == No Symlink ==
# Whether to omit showing symlink targets
# Possible values: false, true
no-symlink: false

# == Total size ==
# Whether to display the total size of directories.
# Possible values: false, true
total-size: true

# == Hyperlink ==
# Attach hyperlink to filenames
# Possible values: always, auto, never
hyperlink: auto

# == Symlink arrow ==
# Specifies how the symlink arrow display, chars in both ascii and utf8
symlink-arrow: ⇒

# == Header ==
# Whether to display block headers.
# Possible values: false, true
header: false

# == Literal ==
# Whether to show quotes on filenames.
# Possible values: false, true
literal: false

# == Truncate owner ==
# How to truncate the username and group names for a file if they exceed a certain
# number of characters.
truncate-owner:
  # Number of characters to keep. By default, no truncation is done (empty value).
  after:
  # String to be appended to a name if truncated.
  marker: ""

  ```
</details>

More on system:
<img width="262" alt="System Information 2024-08-01 19 46 43" src="https://github.com/user-attachments/assets/a3a2d25c-a2d9-4659-a5d9-1399863bf35a">

## Expected behavior
`ls -l`, `ls -Al` and `ls -al` run successfully in root, `.ssh`, and user-created `dev` dirs
(Note `command` is just to escape `ls` alias to `lsd` in fish shell)

<img width="503" alt="Google Chrome 2024-08-01 20 09 15" src="https://github.com/user-attachments/assets/31e3e52a-cf44-4ec0-9ec4-f6b4434df999">
<img width="567" alt="Google Chrome 2024-08-01 20 09 30" src="https://github.com/user-attachments/assets/7efae2e2-f27e-44c8-b7b1-50a95f9c4919">
<img width="534" alt="image" src="https://github.com/user-attachments/assets/b8483a6f-0651-4c0e-8fe3-3d2c4e8a306a">
<img width="552" alt="image" src="https://github.com/user-attachments/assets/9617adc1-78e4-4b7b-88ee-7263e0ca3eeb">

## Actual behavior
`lsd -l`, `lsd -Al` and `lsd -al` fail with `Operation not permitted (os error 1)` and `Permission denied (os error 13)` in different directories but have mixed fail logic.
(Tested in `Warp`, `iTerm2` and mac built-in `Terminal` apps, in `fish` and `zsh` shells)
(`RUST_BACKTRACE=1 lsd ...` produces same result)

`lsd -l`, `lsd -Al` and `lsd -al` fail in root dir
<img width="1315" alt="image" src="https://github.com/user-attachments/assets/95ce2869-a9e2-4c80-9622-827f91cd29f9">
<img width="1285" alt="Google Chrome 2024-08-01 20 10 52" src="https://github.com/user-attachments/assets/2bff077b-6b6d-4fa9-8a25-a9df2b83c397">
<img width="1282" alt="Google Chrome 2024-08-01 20 15 41" src="https://github.com/user-attachments/assets/789c3e08-947a-4044-8e3e-738bda5bc98d">

`lsd -al` fail in `.ssh` and `dev` directores
<img width="1312" alt="Google Chrome 2024-08-01 20 03 25" src="https://github.com/user-attachments/assets/ddaca383-eb04-4286-b688-48c170016d2b">
<img width="1313" alt="Google Chrome 2024-08-01 20 21 32" src="https://github.com/user-attachments/assets/cbda72ac-caac-4ec4-a1ab-562965e5bf36">

**However**, `lsd -l` and `lsd -Al` do not fail in `.ssh` and `dev` dirs
<img width="621" alt="image" src="https://github.com/user-attachments/assets/044c998f-72ab-49a5-8a50-93c2e9ebfefc">
<img width="620" alt="Google Chrome 2024-08-01 20 19 14" src="https://github.com/user-attachments/assets/f8083d66-8d1f-4abb-8cc7-3e5ed9bf18bd">
<img width="650" alt="Google Chrome 2024-08-01 20 24 33" src="https://github.com/user-attachments/assets/2973caff-7c5f-4a1e-bd39-17a3c275a774">
<img width="649" alt="Google Chrome 2024-08-01 20 24 39" src="https://github.com/user-attachments/assets/c83d798c-53a9-4dbc-b594-dabf8ef79651">

## In addition

Running `lsd` in iTerm and Terminal called access prompt on various resources like below, including Full Disk Access. Even after accepting all of them, `lsd` still fails the same way as it does in Warp
<img width="251" alt="UserNotificationCenter 2024-08-01 19 50 13" src="https://github.com/user-attachments/assets/3695545f-bc2a-4505-966c-30076d2da05e">
