### ISSUE TITLE
Can't configure the icons of certain files and directories

### ISSUE THREAD

**Issue by AbubakrBardien** [lsd-rs/lsd#1130]
This is part of what's in my `config.yaml` file:

```yaml
name:
  downloads: 
  music: 
  videos: 
  pictures: 
  README.md:   # doesn't work
  pCloudDrive:   # doesn't work
  viminfo: 

  .editorconfig: 
  .gitignore: 󰊢
  .mozilla: 
  .pki: 
  .styluaignore: 
  .zshenv: 󱆃
```

I don't know what I'm doing wrong here.

OS: Arch Linux
Lsd Version: 1.1.5

The glyphs/icons are from Nerd Fonts, and my terminal, `foot`, can render the other icons.
