### ISSUE TITLE
Icon theme with overrides from config

### ISSUE THREAD

**Issue by ElPapiMango** [lsd-rs/lsd#780]
- os: debian
- `lsd --version`: lsd 0.23.1
- `echo $TERM`: Windows Terminal
- `echo $LS_COLORS`: 

## Current behavior
Created icons.yaml in ~/config/lsd folder based on example in documentation. Docs says
>"The final set of icons used will be a combination of what is shipped with in lsd with overrides from config applied on top of it".

However this does not work for me. Icons from what is shipped is gone anď only this in icons.yaml is used.

Using icon theme. Config.yaml and icons.yaml has a default icon.

![image](https://user-images.githubusercontent.com/43099715/206930946-70bc4e37-f430-40ed-a275-7324ffe89532.png)

Removing icon theme and now config.yaml and icons.yaml have the icon that is shipped.

![image](https://user-images.githubusercontent.com/43099715/206931021-1a0498a6-0bf8-4053-853f-4a63fb8b42ef.png)

**Comment by zwpaper** [comment]
icon theme is currently on master and not yet released, please try to build master or wait until we release 0.24.0

**Comment by matt70tx** [comment]
Using master though and rebuilt it today and same issue.

**Comment by sudame** [comment]
I found that if we set `extension` field in `icons.yaml`, the default theme for `extension` is unexpectedly ignored. The same thing happens when we set `name` field and `filetype` field.

Speaking on a code basis, I believe the following is the cause of this bug.
https://github.com/Peltoche/lsd/blob/da61909835b281d7f7950ec3f763cd077b5b8f02/src/theme.rs#L78-L86

The return value typed `D` has `Default` trait so Serde (Rust's (de)serialize library) will use default field if the field is not set. However in this case a user sets the field so the default field must be ignored.


## example

When you set `icons.yaml` like:
```yaml
extension:
    rs: 🦀 
```

lsd constructs `IconTheme` struct like:
```yaml
name:
    a.out: \u{f489}
    api: \u{f98c}
    # and the other default values...
extension:
    rs: 🦀
    # ↑ only!
filetype:
    dir: \u{f115}
    file: \u{f016}
    # and the other default entries...
```

but we want like this:
```yaml
name:
    a.out: \u{f489}
    api: \u{f98c}
    # and the other default entries...
extension:
    rs: 🦀
    1: \u{f02d}
    2: \u{f02d}
    # and default entries other than those set in the configuration file...
filetype:
    dir: \u{f115}
    file: \u{f016}
    # and the other default values...
```
