### ISSUE TITLE
seperator not rendering between unicode icon and executable filename

### ISSUE THREAD

**Issue by dimitrilw** [lsd-rs/lsd#923]
- os: MacOS Sonoma 14.0, current as of time of this post
- lsd --version: 1.0.0, installed 10 mins ago via Homebrew
- echo $TERM: xterm-256color
- echo $LS_COLORS: none -- empty return value (see pic, below)

![image](https://github.com/lsd-rs/lsd/assets/5898931/c98c3220-2acd-4e1c-b1ec-77403956af0b)

## Expected behavior
Consistent use of `" "` separator between icons and file/directory name, in both short & long output.

## Actual behavior

<img width="922" alt="image" src="https://github.com/lsd-rs/lsd/assets/5898931/1d3c7566-7248-402e-9b07-a2d9d8ab4b18">

<img width="577" alt="image" src="https://github.com/lsd-rs/lsd/assets/5898931/880eecdf-860b-46fc-9694-23ea1f66bd67">

## Relevant section from `~/.config/lsd/config.yaml`

```yaml
# == Icons ==
icons:
  # When to use icons.
  # When "classic" is set, this is set to "never".
  # Possible values: always, auto, never
  when: auto
  # Which icon theme to use.
  # Possible values: fancy, unicode
  #theme: fancy
  # TODO: "fancy" appears to not work with my Mac; nerd font installed, so figure out why
  theme: unicode
  # Separator between icon and the name
  # Default to 1 space
  separator: " "
```
Note: only change made here is switch from `theme: fancy` to `theme: unicode`
